# Generated by Django 4.2.5 on 2023-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='photo',
            field=models.CharField(default='emptynow', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='genus',
            field=models.CharField(max_length=100),
        ),
    ]
