# Generated by Django 4.2.5 on 2023-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_flower_photo_alter_flower_genus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='days_between_watering',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
