# Generated by Django 4.2.5 on 2023-09-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watering_flower_days_between_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='flower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.flower'),
            preserve_default=False,
        ),
    ]
