# Generated by Django 4.2.5 on 2023-09-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_location_alter_watering_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='aridity',
            field=models.CharField(choices=[('D', 'Dry'), ('M', 'Medium'), ('W', 'Wet')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='temperature',
            field=models.CharField(choices=[('C', 'Cold'), ('M', 'Medium'), ('H', 'Hot')], default='C', max_length=1),
        ),
    ]
