# Generated by Django 4.2.5 on 2023-09-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_location_aridity_alter_location_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='preferred_location',
            new_name='viable_locations',
        ),
    ]
